apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment
  namespace: assignment
  labels:
    app: assignment
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: assignment
  template:
    metadata:
      labels:
        app: assignment
    spec:
      imagePullSecrets:
        - name: dockerhub-cred
      automountServiceAccountToken: false
      containers:
        - name: app
          image: docker.io/ale175/service-assignment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
          env:
            # === JWT: letti direttamente dal Secret ===
            - name: JWT_ALGORITHM
              value: RS256
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: assignment-secrets
                  key: jwt_public.pem

            # === Mongo: letti da ConfigMap ===
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: assignment-config        # Deve contenere MONGO_URI
                  key: MONGO_URI_ASSIGNMENTS
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: assignment-config        # Deve contenere MONGO_DB_NAME
                  key: MONGO_DB_NAME_ASSIGNMENTS
                  
            # === RabbitMQ: da secrets ===
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: rabbitmq-password
            - name: RABBITMQ_USERNAME
              valueFrom:  
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: rabbitmq-username
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_USERNAME):$(RABBITMQ_PASSWORD)@rabbitmq.rabbitmq.svc.cluster.local:5672/%2f"

          startupProbe:
            httpGet:
              path: /api/v1/assignments/health
              port: 5050
            periodSeconds: 3
            failureThreshold: 15
          readinessProbe:
            httpGet:
              path: /api/v1/assignments/health
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/assignments/health
              port: 5050
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
