apiVersion: v1
kind: Service
metadata:
  name: assignments-service
  namespace: assignment
spec:
  type: ClusterIP
  selector:
    app: assignment
  ports:
    - port: 5050            
      targetPort: 5050