---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: user-manager
  labels:
    app: mongodb
    component: database
    tier: backend
spec:
  serviceName: mongodb
  replicas: 1
  selector: { matchLabels: { app: mongodb } }
  template:
    metadata: { labels: { app: mongodb } }
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: mongodb
          image: mongo:8.0
          ports: [{ containerPort: 27017 }]
          volumeMounts:
            - name: data
              mountPath: /data/db
          livenessProbe:
            tcpSocket: { port: 27017 }
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            tcpSocket: { port: 27017 }
            initialDelaySeconds: 10
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: microk8s-hostpath
        resources: { requests: { storage: 2Gi } }
