apiVersion: apps/v1
kind: Deployment
metadata:
  name: submission
  namespace: submission
spec:
  replicas: 2
  selector:
    matchLabels:
      app: submission
  template:
    metadata:
      labels:
        app: submission
    spec:
      automountServiceAccountToken: false
      containers:
        - name: app
          image: docker.io/ale175/service-submission:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6060
          env:
            # === JWT: letti direttamente dal Secret ===
            - name: JWT_ALGORITHM
              value: RS256                       # o il tuo algoritmo
            - name: JWT_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-keys                 # Secret esistente nel ns submission
                  key: jwt_public.pem
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-keys
                  key: jwt_private.pem

            # === Mongo: letti da ConfigMap ===
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: submission-config        # Deve contenere MONGO_URI
                  key: MONGO_URI_SUBMISSIONS
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: submission-config        # Deve contenere MONGO_DB_NAME
                  key: MONGO_DB_NAME_SUBMISSIONS

          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 6060
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 6060
            initialDelaySeconds: 10
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
