apiVersion: v1
kind: Service
metadata:
  name: submission-service
  namespace: assignment
spec:
  type: ClusterIP
  selector:
    app: assignment
  ports:
    - port: 6060            
      targetPort: 6060