apiVersion: v1
kind: Service
metadata:
  name: submission-service
  namespace: submission
spec:
  type: ClusterIP
  selector:
    app: submission
  ports:
    - port: 6060            
      targetPort: 6060