apiVersion: v1
kind: Service
metadata:
  name: user-manager-service
  namespace: user-manager
spec:
  type: ClusterIP
  selector:
    app: user-manager
  ports:
    - port: 5050            
      targetPort: 5050